package ch.epfl.cs311.wanderwave.ui.screens

import androidx.compose.material3.Text
import androidx.compose.runtime.Composable

@Composable
fun DummyScreen() {
  // Dummy screen to see if this can pass without needing coverage
  // Delete once verified
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
  Text(text = "Dummy Screen 2")
}
